---
title: "New Tasks"
author: "Fabian Schroeder"
date: "June 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* **Task 17** Choose a (first) model for a predictor. Clearly state your modelling assumptions and any decisions you made also during the foramting of the data, e.g. 

    - use only results after 90 minutes.
    - use only data after 1994
    - which identifier was used to merge the data sets.

Since the data availability varies between data sets, clearly state how you want to fit and evaluate your predictor. The availability of the selected data sets is as follows:

    - Historic WC data is available since the 1930s
    - FIFA ranks are available since 1993, 
    - the full player's data is available for the 2018 world cup only,
    - the market value of a player is available since 2006.

For other sources of data the availability might be different. Thus, we need a good strategy for bulding a classifier and evaluating it.

If you want to use information such as scored goals, caps, etc. for every player, then the only possiblity would be the qualifiers. Where can be obtain the results?


* **Task 18** You do not have to use a statistical model, but if you do, you have to train it. This would require a trainings dataset. This training set would need include at least

- the result of the game
- general information about the game
- information about the home team
- information about the away team


* **Task 19** (voluntary) Create a list of pariticipating nations for every world cup and scrape their information from the follwing links:

[https://www.transfermarkt.de/weltmeisterschaft-2014/teilnehmer/pokalwettbewerb/WM14/saison_id/2013](https://www.transfermarkt.de/weltmeisterschaft-2014/teilnehmer/pokalwettbewerb/WM14/saison_id/2013)

[https://www.transfermarkt.de/weltmeisterschaft-2010/teilnehmer/pokalwettbewerb/WM10/saison_id/2009](https://www.transfermarkt.de/weltmeisterschaft-2010/teilnehmer/pokalwettbewerb/WM10/saison_id/2009)

[https://www.transfermarkt.de/weltmeisterschaft-2006/teilnehmer/pokalwettbewerb/WM06/saison_id/2005](https://www.transfermarkt.de/weltmeisterschaft-2006/teilnehmer/pokalwettbewerb/WM06/saison_id/2005)

[https://www.transfermarkt.de/weltmeisterschaft-2002/teilnehmer/pokalwettbewerb/WM02/saison_id/2001](https://www.transfermarkt.de/weltmeisterschaft-2002/teilnehmer/pokalwettbewerb/WM02/saison_id/2001)




